"""Legal document templates for WiFi privacy defense.

All templates generate Markdown text with appropriate legal disclaimers.
Templates cover FCC complaints, cease-and-desist letters, and incident reports
related to unauthorized radio frequency surveillance and privacy-invasive sensing.

NOTE: These documents are NOT legal advice. See DISCLAIMER constant.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Final


DISCLAIMER: Final[str] = (
    "DISCLAIMER: This document is generated by automated software and does NOT "
    "constitute legal advice. The information provided is for informational purposes "
    "only. Consult a licensed attorney in your jurisdiction before taking any legal "
    "action. Laws regarding WiFi sensing, surveillance, and privacy vary significantly "
    "by jurisdiction. No attorney-client relationship is created by use of this software."
)


class FCCComplaintTemplate:
    """Generates FCC complaint content from detection evidence.

    Produces a formatted complaint citing relevant FCC regulations including
    47 CFR Part 15 and 47 USC 333 where active transmission is involved.
    """

    def render(
        self,
        complainant_name: str = "[YOUR NAME]",
        complainant_address: str = "[YOUR ADDRESS]",
        suspect_address: str = "[SUSPECTED OPERATOR ADDRESS]",
        detection_summary: str = "",
        devices: list[dict] | None = None,
        timeline: list[dict] | None = None,
    ) -> str:
        """Render FCC complaint as Markdown.

        Args:
            complainant_name: Name of the person filing the complaint.
            complainant_address: Address of the complainant.
            suspect_address: Address of the suspected operator.
            detection_summary: Summary text of what was detected.
            devices: List of device dicts with keys like mac_address, vendor, etc.
            timeline: List of timeline event dicts with keys like timestamp, event.

        Returns:
            Markdown-formatted FCC complaint document.
        """
        devices = devices or []
        timeline = timeline or []

        lines: list[str] = []
        lines.append(f"> {DISCLAIMER}")
        lines.append("")
        lines.append("# FCC Complaint — Unauthorized Radio Frequency Surveillance")
        lines.append("")
        lines.append(f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")
        lines.append("")

        # Section 1: Complainant Information
        lines.append("## 1. Complainant Information")
        lines.append("")
        lines.append(f"- **Name:** {complainant_name}")
        lines.append(f"- **Address:** {complainant_address}")
        lines.append("")

        # Section 2: Subject of Complaint
        lines.append("## 2. Subject of Complaint")
        lines.append("")
        lines.append(
            f"- **Suspected Operator Address:** {suspect_address}"
        )
        lines.append(
            "- **Activity:** Unauthorized WiFi-based sensing and surveillance "
            "of occupied residential premises."
        )
        lines.append("")

        # Section 3: Nature of Complaint
        lines.append("## 3. Nature of Complaint")
        lines.append("")
        lines.append(
            "The complainant has detected evidence of unauthorized radio frequency "
            "surveillance directed at their residence. WiFi Channel State Information "
            "(CSI) sensing technology appears to be used to monitor physical activity, "
            "breathing patterns, or presence within the home without consent."
        )
        lines.append("")
        if detection_summary:
            lines.append(f"**Detection Summary:** {detection_summary}")
            lines.append("")

        # Section 4: Rules Believed Violated
        lines.append("## 4. Rules Believed Violated")
        lines.append("")
        lines.append(
            "- **47 CFR Part 15** — Unlicensed devices must not cause harmful "
            "effects to authorized radio services or be operated in a manner "
            "inconsistent with their authorization."
        )
        lines.append(
            "- **47 USC 333** — If active probing or transmission is involved, "
            "willful or malicious use of a radio device to cause unauthorized "
            "surveillance may violate federal communications law."
        )
        lines.append(
            "- The use of WiFi CSI data to conduct through-wall sensing of "
            "human biometric activity (breathing, heartbeat, motion) without "
            "consent raises significant privacy concerns under the spirit of "
            "FCC regulations governing radio frequency devices."
        )
        lines.append("")

        # Section 5: Evidence Summary
        lines.append("## 5. Evidence Summary")
        lines.append("")
        if devices:
            lines.append("### Detected Devices")
            lines.append("")
            lines.append("| MAC Address | Vendor | First Seen | Last Seen |")
            lines.append("|---|---|---|---|")
            for dev in devices:
                mac = dev.get("mac_address", "Unknown")
                vendor = dev.get("vendor", "Unknown")
                first = dev.get("first_seen", "N/A")
                last = dev.get("last_seen", "N/A")
                lines.append(f"| {mac} | {vendor} | {first} | {last} |")
            lines.append("")

        if timeline:
            lines.append("### Detection Timeline")
            lines.append("")
            lines.append("| Timestamp | Event | Details |")
            lines.append("|---|---|---|")
            for event in timeline:
                ts = event.get("timestamp", "N/A")
                evt = event.get("event", "N/A")
                details = event.get("details", "")
                lines.append(f"| {ts} | {evt} | {details} |")
            lines.append("")

        if not devices and not timeline:
            lines.append("*See attached detection log for technical evidence.*")
            lines.append("")

        # Section 6: Requested Action
        lines.append("## 6. Requested Action")
        lines.append("")
        lines.append(
            "The complainant respectfully requests that the Federal Communications "
            "Commission:"
        )
        lines.append("")
        lines.append(
            "1. Investigate the reported unauthorized radio frequency surveillance "
            "activity."
        )
        lines.append(
            "2. Determine whether the operation of the identified device(s) "
            "violates 47 CFR Part 15 or 47 USC 333."
        )
        lines.append(
            "3. Take appropriate enforcement action if violations are confirmed."
        )
        lines.append(
            "4. Issue guidance on the legality of WiFi CSI-based through-wall "
            "sensing directed at occupied residences."
        )
        lines.append("")

        # Section 7: Declaration
        lines.append("## 7. Declaration")
        lines.append("")
        lines.append(
            "I declare under penalty of perjury that the information contained "
            "in this complaint is true and correct to the best of my knowledge."
        )
        lines.append("")
        lines.append(f"**Signature:** ________________________")
        lines.append(f"**Printed Name:** {complainant_name}")
        lines.append(
            f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
        )
        lines.append("")

        return "\n".join(lines)


class CeaseAndDesistTemplate:
    """Generates cease-and-desist letter content.

    Adapts legal basis by state, including Illinois BIPA, California
    CCPA/CPRA, common law intrusion upon seclusion, and state wiretap laws.
    """

    # State-specific legal bases
    _STATE_LEGAL_BASES: Final[dict[str, list[str]]] = {
        "illinois": [
            "Illinois Biometric Information Privacy Act (BIPA), 740 ILCS 14 — "
            "Provides a private right of action with statutory damages of $1,000 "
            "per negligent violation and $5,000 per intentional or reckless violation "
            "for collection of biometric data (including physiological measurements) "
            "without informed written consent.",
        ],
        "california": [
            "California Consumer Privacy Act / California Privacy Rights Act "
            "(CCPA/CPRA), Cal. Civ. Code 1798.100 et seq. — Protects consumers' "
            "physiological and behavioral characteristics as personal information. "
            "Provides rights to know, delete, and opt out of collection.",
            "California Invasion of Privacy Act (CIPA), Cal. Penal Code 630 et seq. "
            "— Prohibits eavesdropping and surveillance technologies directed at "
            "private residences.",
        ],
        "texas": [
            "Texas Capture or Use of Biometric Identifier Act (CUBI), Tex. Bus. & "
            "Com. Code 503.001 — Prohibits capture of biometric identifiers without "
            "informed consent. Attorney General enforcement with penalties up to "
            "$25,000 per violation.",
        ],
        "washington": [
            "Washington Biometric Identifiers statute, RCW 19.375 — Requires notice "
            "and consent before enrolling biometric identifiers in a database.",
        ],
    }

    def render(
        self,
        sender_name: str = "[YOUR NAME]",
        sender_address: str = "[YOUR ADDRESS]",
        recipient_name: str = "[RECIPIENT NAME]",
        recipient_address: str = "[RECIPIENT ADDRESS]",
        detection_summary: str = "",
        state: str = "",
    ) -> str:
        """Render cease-and-desist letter as Markdown.

        Args:
            sender_name: Name of the person sending the letter.
            sender_address: Address of the sender.
            recipient_name: Name of the recipient.
            recipient_address: Address of the recipient.
            detection_summary: Summary of detected surveillance activity.
            state: US state (lowercase) for state-specific legal citations.

        Returns:
            Markdown-formatted cease-and-desist letter.
        """
        lines: list[str] = []
        lines.append(f"> {DISCLAIMER}")
        lines.append("")
        lines.append("# Cease and Desist — Unauthorized WiFi Surveillance")
        lines.append("")
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines.append(f"**Date:** {date_str}")
        lines.append("")

        # Section 1: Identification
        lines.append("## 1. Identification of Parties")
        lines.append("")
        lines.append(f"**From:**")
        lines.append(f"- {sender_name}")
        lines.append(f"- {sender_address}")
        lines.append("")
        lines.append(f"**To:**")
        lines.append(f"- {recipient_name}")
        lines.append(f"- {recipient_address}")
        lines.append("")

        # Section 2: Description of Activity
        lines.append("## 2. Description of Unauthorized Activity")
        lines.append("")
        lines.append(
            "It has come to my attention that radio frequency sensing technology "
            "is being operated from or near your premises in a manner that monitors "
            "physical activity, biometric indicators, and/or presence within my "
            "private residence without my knowledge or consent."
        )
        lines.append("")
        lines.append(
            "Specifically, WiFi Channel State Information (CSI) analysis has "
            "been detected that is capable of through-wall sensing of human "
            "breathing patterns, heartbeat, motion, and presence. This constitutes "
            "unauthorized radio frequency surveillance of my private dwelling."
        )
        lines.append("")
        if detection_summary:
            lines.append(f"**Detected Activity:** {detection_summary}")
            lines.append("")

        # Section 3: Legal Basis
        lines.append("## 3. Legal Basis")
        lines.append("")

        # Common law basis (always included)
        lines.append(
            "- **Common Law Intrusion Upon Seclusion** — Through-wall monitoring "
            "of a person's physical activities and biometric data within their "
            "home constitutes a highly offensive intrusion into a matter in which "
            "the occupant has a reasonable expectation of privacy."
        )
        lines.append(
            "- **Kyllo v. United States, 533 U.S. 27 (2001)** — The Supreme Court "
            "held that the use of sense-enhancing technology to obtain information "
            "about the interior of a home that could not otherwise be obtained "
            "without physical intrusion constitutes a search. While this case "
            "constrains government actors, it establishes the legal principle "
            "that through-wall sensing of a home invades reasonable privacy "
            "expectations."
        )
        lines.append(
            "- **State Wiretap and Surveillance Laws** — Many states prohibit "
            "electronic surveillance of private premises without consent under "
            "their wiretapping or eavesdropping statutes."
        )

        # State-specific legal bases
        state_lower = state.lower().strip()
        if state_lower in self._STATE_LEGAL_BASES:
            for basis in self._STATE_LEGAL_BASES[state_lower]:
                lines.append(f"- **{basis.split('—')[0].strip()}** — {basis}")
        lines.append("")

        # Section 4: Specific Demands
        lines.append("## 4. Specific Demands")
        lines.append("")
        lines.append("You are hereby demanded to immediately:")
        lines.append("")
        lines.append(
            "1. **Cease** all WiFi-based sensing, monitoring, and surveillance "
            "activities directed at my residence."
        )
        lines.append(
            "2. **Disable** any devices, software, or configurations being used "
            "to collect Channel State Information or other radio frequency data "
            "from my premises."
        )
        lines.append(
            "3. **Delete** all data collected from monitoring my residence, "
            "including any biometric, physiological, or behavioral data derived "
            "from WiFi sensing."
        )
        lines.append(
            "4. **Confirm** in writing within fourteen (14) days of receipt of "
            "this letter that you have complied with all of the above demands."
        )
        lines.append("")

        # Section 5: Consequences
        lines.append("## 5. Consequences of Non-Compliance")
        lines.append("")
        lines.append(
            "Failure to comply with these demands may result in the following "
            "actions:"
        )
        lines.append("")
        lines.append("- Filing of a complaint with the Federal Communications Commission (FCC).")
        lines.append("- Filing of a complaint with state law enforcement authorities.")
        lines.append("- Initiation of civil litigation seeking injunctive relief and damages.")
        if state_lower == "illinois":
            lines.append(
                "- Pursuit of statutory damages under Illinois BIPA ($1,000-$5,000 "
                "per violation)."
            )
        elif state_lower == "california":
            lines.append(
                "- Exercise of rights under CCPA/CPRA and pursuit of remedies "
                "under the California Invasion of Privacy Act."
            )
        lines.append("")

        # Section 6: Preservation Demand
        lines.append("## 6. Evidence Preservation Demand")
        lines.append("")
        lines.append(
            "You are hereby notified that you have a legal obligation to preserve "
            "all evidence related to the activities described in this letter, "
            "including but not limited to:"
        )
        lines.append("")
        lines.append("- All device logs, configuration files, and network records.")
        lines.append("- All collected sensor data, CSI data, and derived analytics.")
        lines.append("- All communications related to WiFi sensing or monitoring activities.")
        lines.append("- All hardware devices used in the surveillance activity.")
        lines.append("")
        lines.append(
            "Destruction, alteration, or concealment of evidence may constitute "
            "spoliation and give rise to adverse inferences in any subsequent "
            "legal proceedings."
        )
        lines.append("")

        lines.append("**Respectfully,**")
        lines.append("")
        lines.append(f"________________________")
        lines.append(f"{sender_name}")
        lines.append(f"{sender_address}")
        lines.append(f"{date_str}")
        lines.append("")

        return "\n".join(lines)


class IncidentReportTemplate:
    """Generates incident report for law enforcement.

    Structures detected surveillance evidence into a format suitable
    for filing with local law enforcement agencies.
    """

    def render(
        self,
        reporter_name: str = "[YOUR NAME]",
        reporter_address: str = "[YOUR ADDRESS]",
        detection_summary: str = "",
        devices: list[dict] | None = None,
        timeline: list[dict] | None = None,
    ) -> str:
        """Render incident report as Markdown.

        Args:
            reporter_name: Name of the person filing the report.
            reporter_address: Address of the reporter.
            detection_summary: Summary of detected surveillance activity.
            devices: List of device dicts with keys like mac_address, vendor, etc.
            timeline: List of timeline event dicts with keys like timestamp, event.

        Returns:
            Markdown-formatted incident report.
        """
        devices = devices or []
        timeline = timeline or []

        lines: list[str] = []
        lines.append(f"> {DISCLAIMER}")
        lines.append("")
        lines.append("# Incident Report — Unauthorized WiFi Surveillance")
        lines.append("")
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines.append(f"**Report Date:** {date_str}")
        lines.append(f"**Report Number:** AUTO-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}")
        lines.append("")

        # Section 1: Reporter Information
        lines.append("## 1. Reporter Information")
        lines.append("")
        lines.append(f"- **Name:** {reporter_name}")
        lines.append(f"- **Address:** {reporter_address}")
        lines.append("")

        # Section 2: Incident Description
        lines.append("## 2. Incident Description")
        lines.append("")
        lines.append(
            "The reporter has detected evidence of unauthorized radio frequency "
            "surveillance targeting their private residence using WiFi Channel "
            "State Information (CSI) sensing technology. This technology enables "
            "through-wall monitoring of human physical activity, breathing patterns, "
            "heartbeat, and presence without the knowledge or consent of the occupants."
        )
        lines.append("")
        if detection_summary:
            lines.append(f"**Summary:** {detection_summary}")
            lines.append("")

        # Section 3: Technical Evidence
        lines.append("## 3. Technical Evidence")
        lines.append("")
        if devices:
            lines.append("### Suspicious Devices Detected")
            lines.append("")
            lines.append("| # | MAC Address | Vendor | Channels | Frame Count |")
            lines.append("|---|---|---|---|---|")
            for i, dev in enumerate(devices, 1):
                mac = dev.get("mac_address", "Unknown")
                vendor = dev.get("vendor", "Unknown")
                channels = dev.get("channels_observed", [])
                ch_str = ", ".join(str(c) for c in channels) if channels else "N/A"
                frames = dev.get("frame_count", "N/A")
                lines.append(f"| {i} | {mac} | {vendor} | {ch_str} | {frames} |")
            lines.append("")

        if timeline:
            lines.append("### Event Timeline")
            lines.append("")
            lines.append("| # | Timestamp | Event | Severity | Details |")
            lines.append("|---|---|---|---|---|")
            for i, event in enumerate(timeline, 1):
                ts = event.get("timestamp", "N/A")
                evt = event.get("event", "N/A")
                sev = event.get("severity", "N/A")
                details = event.get("details", "")
                lines.append(f"| {i} | {ts} | {evt} | {sev} | {details} |")
            lines.append("")

        if not devices and not timeline:
            lines.append("*Technical evidence is recorded in the attached signed log files.*")
            lines.append("")

        # Section 4: Impact Statement
        lines.append("## 4. Impact Statement")
        lines.append("")
        lines.append(
            "The unauthorized surveillance of my private residence constitutes "
            "a significant invasion of privacy. WiFi CSI sensing can reveal:"
        )
        lines.append("")
        lines.append("- **Presence:** Whether occupants are home or away.")
        lines.append("- **Motion:** Movement patterns and activity levels within the home.")
        lines.append("- **Breathing:** Respiratory rate of occupants (indicative of sleep, stress, health).")
        lines.append("- **Heartbeat:** Cardiac rhythm (sensitive health information).")
        lines.append("- **Gestures:** Hand and body movements.")
        lines.append("")
        lines.append(
            "This level of surveillance within a private home is profoundly "
            "invasive and causes reasonable concern for personal safety and security."
        )
        lines.append("")

        # Section 5: Requested Action
        lines.append("## 5. Requested Action")
        lines.append("")
        lines.append("The reporter respectfully requests that law enforcement:")
        lines.append("")
        lines.append("1. Document this report for the official record.")
        lines.append(
            "2. Investigate the source of the unauthorized radio frequency "
            "surveillance activity."
        )
        lines.append(
            "3. Determine whether the surveillance activity violates applicable "
            "state or federal laws."
        )
        lines.append("4. Take appropriate enforcement action to stop the unauthorized surveillance.")
        lines.append("")

        lines.append("**Reporter Signature:** ________________________")
        lines.append(f"**Printed Name:** {reporter_name}")
        lines.append(
            f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
        )
        lines.append("")

        return "\n".join(lines)
